
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Drawing;
using static PictureBoxSqlServer_efcore.Classes.ImageHelpers;

#nullable disable

namespace PictureBoxSqlServer_efcore.Models
{
    public partial class Categories
    {
        private Image _image;

        /// <summary>
        /// Primary key
        /// </summary>
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string Description { get; set; }
        public byte[] Picture { get; set; }
        public Image Image => ByteArrayToImage(Picture);
        public override string ToString() => CategoryName;

    }
}