// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataAnnotationsEntityFrameworkCoreDates.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

#nullable disable

namespace DataAnnotationsEntityFrameworkCoreDates.DbContext
{
    public class SalesConfiguration : IEntityTypeConfiguration<Sales>
    {
        public void Configure(EntityTypeBuilder<Sales> entity)
        {
            entity.Property(e => e.SaleDate).HasDefaultValueSql("(getdate())");
        }
    }
}
