// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Switches.Models
{
    public partial class WeekDayName
    {
        public WeekDayName()
        {
            CourseDay = new HashSet<CourseDay>();
        }

        public int WeekId { get; set; }
        public string DayName { get; set; }

        public virtual ICollection<CourseDay> CourseDay { get; set; }
    }
}