
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using DataAnnotationsEntityFrameworkCoreDates.Classes;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace DataAnnotationsEntityFrameworkCoreDates.Models
{
    public partial class Person1
    {
        [Key]
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        /// <summary>
        /// 'DisplayFormat' annotations for ASP.NET Core
        /// </summary>
        [Display(Name = "Date of birth")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        [Column(TypeName = "date")]
        public DateTime? BirthDate { get; set; }
        /// <summary>
        /// For desktop apps
        /// </summary>
        public string BirthDateFormatted 
            => BirthDate?.Age(DateTime.Now).YearsMonthsDays;

    }
}