
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.CompilerServices;
using DataAnnotationsEntityFrameworkCoreDates.Classes;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace DataAnnotationsEntityFrameworkCoreDates.Models
{
    public partial class Person1 : INotifyPropertyChanged
    {
        private DateTime? _birthDate;

        [Key]
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }

        [Column(TypeName = "date")]
        public DateTime? BirthDate
        {
            get => _birthDate;
            set
            {
                _birthDate = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// For desktop apps
        /// </summary>
        public string BirthDateFormatted 
            => BirthDate?.Age(DateTime.Now).YearsMonthsDays;

        public event PropertyChangedEventHandler PropertyChanged;
        protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }

    }
}