// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Switches.Data;
using Switches.Models;
using System;

namespace Switches.Data.Configurations
{
    public partial class CourseDayConfiguration : IEntityTypeConfiguration<CourseDay>
    {
        public void Configure(EntityTypeBuilder<CourseDay> entity)
        {
            entity.Property(e => e.Offered).HasDefaultValueSql("((0))");

            entity.HasOne(d => d.DayIndexNavigation)
                .WithMany(p => p.CourseDay)
                .HasForeignKey(d => d.DayIndex)
                .HasConstraintName("FK_CourseDay_WeekDay");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CourseDay> entity);
    }
}
