// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Switches.Data;
using Switches.Models;
using System;

namespace Switches.Data.Configurations
{
    public partial class OnlineCourseConfiguration : IEntityTypeConfiguration<OnlineCourse>
    {
        public void Configure(EntityTypeBuilder<OnlineCourse> entity)
        {
            entity.HasKey(e => e.CourseID);

            entity.Property(e => e.CourseID).ValueGeneratedNever();

            entity.Property(e => e.URL)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.Course)
                .WithOne(p => p.OnlineCourse)
                .HasForeignKey<OnlineCourse>(d => d.CourseID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OnlineCourse_Course");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<OnlineCourse> entity);
    }
}
