// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Switches.Data;
using Switches.Models;
using System;

namespace Switches.Data.Configurations
{
    public partial class WeekDayNameConfiguration : IEntityTypeConfiguration<WeekDayName>
    {
        public void Configure(EntityTypeBuilder<WeekDayName> entity)
        {
            entity.HasKey(e => e.WeekId)
                .HasName("PK_WeekDay");

            entity.Property(e => e.DayName).IsRequired();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<WeekDayName> entity);
    }
}
